apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: grafana-image
          imagePullPolicy: Never
          volumeMounts:
            - name: grafana-config
              subPath: grafana.ini
              mountPath: /etc/grafana/grafana.ini
              readOnly: true
          envFrom:
            - secretRef:
                name: grafana-secret
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
